# main test workflow; ported from .travis.yaml

name: main

on:
  schedule:
    - cron:  '* * * * 5'   # Runs on every Friday.
  push:
    branches: [ '*', $default-branch ]
    tags: ['[0-9]*']   # anything looks like a version.
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.8 ]
        include:
          - {deploy: true, os: ubuntu-latest, python-version: 3.8 }
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup test env
      run: |
        python -m pip install tox-gh

    - name: Python Unit tests
      run: |
        tox4

    - name: Build Python sdist
      if: startsWith(github.ref, 'refs/tags') && matrix.deploy
      run: |
        python setup.py sdist

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      if: startsWith(github.ref, 'refs/tags') && matrix.deploy
      with:
        password: ${{ secrets.PYPI_SECRET }}
